In [1]:
import h5py 
import numpy as np
fs  = h5py.File("FeatureMatrix_trainedmodel.hdf5","r")
ds = fs["featuresmatrix"]

In [2]:
ds_arr = ds[:]
ytarget=np.load("YpredforClassesWname.npy")
print(ytarget.shape)
print(ds_arr.shape)

(7872, 2)
(7872, 2048)


In [3]:
total = np.concatenate((ds_arr,ytarget[:,1].reshape(-1,1)),axis=1).astype("float32")

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(total[:,:-1], total[:,-1], test_size = 0.1, random_state = 0)

In [5]:
print(X_train)
import lightgbm as lgb
clf = lgb.LGBMClassifier(n_estimators=1000)
clf.fit(X_train, y_train)
# predict the results
y_pred=clf.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_pred, y_test)
print('LightGBM Model accuracy score: {0:0.4f}'.format(accuracy_score(y_test, y_pred)))

[[  0.          60.105076     0.         ...   1.6668444    0.55340534
    0.        ]
 [  0.          48.090134     0.         ...   0.           0.5371359
    0.        ]
 [  0.          54.250893     0.         ...   0.           0.6163479
    0.        ]
 ...
 [  0.          74.922195     0.         ...  10.39827      0.47490913
    0.        ]
 [  0.         109.463135     0.         ...   0.           1.6297406
    0.        ]
 [  0.          81.434784     0.         ...   0.           0.47103834
    0.        ]]
LightGBM Model accuracy score: 0.8058


In [6]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix\n\n', cm)
print('\nTrue Positives(TP) = ', cm[0,0])
print('\nTrue Negatives(TN) = ', cm[1,1])
print('\nFalse Positives(FP) = ', cm[0,1])
print('\nFalse Negatives(FN) = ', cm[1,0])

Confusion matrix

 [[231  12  27]
 [ 35 196  26]
 [ 35  18 208]]

True Positives(TP) =  231

True Negatives(TN) =  196

False Positives(FP) =  12

False Negatives(FN) =  35


In [7]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.77      0.86      0.81       270
         1.0       0.87      0.76      0.81       257
         2.0       0.80      0.80      0.80       261

    accuracy                           0.81       788
   macro avg       0.81      0.81      0.81       788
weighted avg       0.81      0.81      0.81       788

